version: "3.9"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: socialmedia
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - db

volumes:
  db-data:
